set -sg escape-time 0
unbind C-b
set -g prefix M-a
# set -g status off

bind C-l send-keys C-l
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-k select-pane -U
bind -n C-j select-pane -D

if-shell "grep -q 'moon.png' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#FFFF01',fg=black; set -g pane-active-border-style fg='#FFFF01'"

if-shell "grep -q 'bleach.jpeg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#FF8704',fg=black; set -g pane-active-border-style fg='#FF8704'"
if-shell "grep -q 'bleach2.jpg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#FF8704',fg=black; set -g pane-active-border-style fg='#FF8704'"

if-shell "grep -q 'ichigo.jpg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#FF8704',fg=black; set -g pane-active-border-style fg='#FF8704'"

if-shell "grep -q 'rukia2.png' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#FF8704',fg=black; set -g pane-active-border-style fg='#FF8704'"

if-shell "grep -q 'rukia.jpg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#80A2CF',fg=black; set -g pane-active-border-style fg='#80A2CF'"


if-shell "grep -q 'kessoku.png' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#F3ABB9',fg=black; set -g pane-active-border-style fg='#F3ABB9'"

if-shell "grep -q 'katanazero.png' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#58377F',fg=black; set -g pane-active-border-style fg='#58377F'"

if-shell "grep -q 'ed.jpg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#BF252D',fg=black; set -g pane-active-border-style fg='#BF252D'"

if-shell "grep -q 'ed2.jpg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#E6C345',fg=black; set -g pane-active-border-style fg='#E6C345'"

if-shell "grep -q 'ed3.png ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#9A3537',fg=black; set -g pane-active-border-style fg='#9A3537'"

if-shell "grep -q 'philedelphia.jpg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#BF252D',fg=black; set -g pane-active-border-style fg='#BF252D'"

if-shell "! grep -qE 'moon.png|bleach.jpeg|ichigo.jpg|rukia2.png|rukia.jpg|kessoku.png|katanazero.png|ed.jpg|ed2.jpg|ed3.png|philedelphia.jpg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#333333',fg=white; set -g pane-active-border-style fg='#333333'"

bind s split-window -h
bind v split-window -v

bind r source-file "~/.config/tmux/tmux.conf"

bind h resize-pane -L 60
bind l resize-pane -R 60
bind k resize-pane -U 60
bind j resize-pane -D 60

bind d detach
