set -sg escape-time 0
unbind C-b
set -g prefix M-a
# set -g status off

bind C-l send-keys C-l
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-k select-pane -U
bind -n C-j select-pane -D

if-shell "grep -q 'moon.png' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#FFFF01',fg=black; set -g pane-active-border-style fg='#FFFF01'"

if-shell "grep -q 'bleach.jpeg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#FF8704',fg=black; set -g pane-active-border-style fg='#FF8704'"

if-shell "! grep -qE 'moon.png|bleach.jpeg' ~/nixdots/modules/home/configs/quickshell/wallpaper.conf" "set -g status-style bg='#333333',fg=white; set -g pane-active-border-style fg='#333333'"

bind s split-window -h
bind v split-window -v

bind h resize-pane -L 60
bind l resize-pane -R 60
bind k resize-pane -U 60
bind j resize-pane -D 60

bind d detach
