bind=SUPER,r,reload_config

bind=SUPER,space,spawn,qs ipc call launcher toggle
bind=SUPER,Return,spawn,ghostty
bind=SUPER,B,spawn,zen
bind=SUPER+SHIFT,B,spawn,zen --private-window


bind=SUPER,s,spawn, grim  "/home/$USER/Screenshots/$(date "+%Y-%m-%d %H:%M:%S").png"
bind=SUPER+SHIFT,s,spawn, grim -g "$(slurp)" "/home/$USER/Screenshots/$(date "+%Y-%m-%d %H:%M:%S").png"
bind=SUPER,c,spawn,ghostty -e sh -c "cd ~/nixdots && nvim .; exec $SHELL"
bind=SUPER+SHIFt,c,spawn,ghostty -e sh -c "cd ~/.config/mango && nvim .; exec $SHELL"

bind=SUPER,m,quit
bind=SUPER,q,killclient,

bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=ALT,backslash,togglefloating,
bind=SUPER,f,togglefullscreen,

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,
bind=alt+super+ctrl,Left,scroller_stack,left
bind=alt+super+ctrl,Right,scroller_stack,right
bind=alt+super+ctrl,Up,scroller_stack,up
bind=alt+super+ctrl,Down,scroller_stack,down

#dwindle layout(manual split mode)
bind=alt+shift,Return,dwindle_toggle_split_direction

# switch layout
bind=SUPER,n,switch_layout

# tag switch
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

binds=none,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 2%+
binds=none,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 2%-
binds=none,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=none,XF86AudioPlay,spawn,playerctl play-pause
bind=none,F8,spawn,playerctl play-pause
bind=none,XF86AudioStop,spawn,playerctl stop
bind=none,XF86AudioNext,spawn,playerctl next 
bind=none,F9,spawn,playerctl next 
bind=none,XF86AudioPrev,spawn,playerctl previous 
bind=none,F7,spawn,playerctl previous 


# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# movewin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

bind=SUPER,Tab,viewtoright
bind=SUPER+SHIFT,Tab,viewtoleft

bind=SUPER,XF86AudioRaiseVolume,viewtoright
bind=SUPER,XF86AudioLowerVolume,viewtoleft



# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
