# More option see https://github.com/DreamMaoMao/mango/wiki/
#
exec=pkill .quickshell-wra;quickshell
# exec=pkill swaybg;swaybg -i ~/.config/mango/wallp/moon.png
exec=pkill neko-mangowm;neko-mangowm HDMI-A-1
exec=pkill awww-daemon-wr;awww-daemon

source=./bind.conf
source=./theme.conf
source=./layout.conf
