# More option see https://github.com/DreamMaoMao/mango/wiki/
#
exec=pkill .quickshell-wra;qs 
exec=pkill swaybg;swaybg -i ~/.config/mango/wallp/moon.png
exec=neko-mangowm HDMI-A-1

source=./bind.conf
source=./theme.conf
source=./layout.conf
